export default {
  bgColor: '#eef4f8',
  primary: '#3E525E',
  primaryText: '#8ba5b4',
  primaryInactive: '#deeaef',
  primaryActive: '#2D3F4A',
  primaryTilt: '#f8fafb',
  secondary: '#47C9DD',
  tertiary: '#F9C242',
  secondaryText: '#212529',
  greyText: '#8a8a8a',
  white: '#FFF',
  black: '#000',
  red: 'red',
};
