import {SOCKET_CONFIG} from '../../env.json';

const Discriminator = {
  BL: 'Live Blog',
  LQ: 'Live QA',
};
const pageSize = 10;

const manageApps = [
  // 'apps',
  // 'groupApps',
  // 'directApps',
  'blogApps',
  'boothChatApps',
  'liveApps',
];
const translations = [
  {
    name: 'Afrikaans',
    nativeName: 'Afrikaans',
    dir: 'ltr',
    code: 'af',
  },
  {
    name: 'Arabic',
    nativeName: 'العربية',
    dir: 'rtl',
    code: 'ar',
  },
  {
    name: 'Bulgarian',
    nativeName: 'Български',
    dir: 'ltr',
    code: 'bg',
  },
  {
    name: 'Bangla',
    nativeName: 'বাংলা',
    dir: 'ltr',
    code: 'bn',
  },
  {
    name: 'Bosnian',
    nativeName: 'bosanski (latinica)',
    dir: 'ltr',
    code: 'bs',
  },
  {
    name: 'Catalan',
    nativeName: 'Català',
    dir: 'ltr',
    code: 'ca',
  },
  {
    name: 'Chinese Simplified',
    nativeName: '简体中文',
    dir: 'ltr',
    code: 'zh-Hans',
  },
  {
    name: 'Czech',
    nativeName: 'Čeština',
    dir: 'ltr',
    code: 'cs',
  },
  {
    name: 'Welsh',
    nativeName: 'Welsh',
    dir: 'ltr',
    code: 'cy',
  },
  {
    name: 'Danish',
    nativeName: 'Dansk',
    dir: 'ltr',
    code: 'da',
  },
  {
    name: 'German',
    nativeName: 'Deutsch',
    dir: 'ltr',
    code: 'de',
  },
  {
    name: 'Greek',
    nativeName: 'Ελληνικά',
    dir: 'ltr',
    code: 'el',
  },
  {
    name: 'Spanish',
    nativeName: 'Español',
    dir: 'ltr',
    code: 'es',
  },
  {
    name: 'Estonian',
    nativeName: 'Eesti',
    dir: 'ltr',
    code: 'et',
  },
  {
    name: 'Persian',
    nativeName: 'Persian',
    dir: 'rtl',
    code: 'fa',
  },
  {
    name: 'Finnish',
    nativeName: 'Suomi',
    dir: 'ltr',
    code: 'fi',
  },
  {
    name: 'Faroese',
    nativeName: 'Haitian Creole',
    dir: 'ltr',
    code: 'ht',
  },
  {
    name: 'French',
    nativeName: 'Français',
    dir: 'ltr',
    code: 'fr',
  },
  {
    name: 'Hebrew',
    nativeName: 'עברית',
    dir: 'rtl',
    code: 'he',
  },
  {
    name: 'Hindi',
    nativeName: 'हिंदी',
    dir: 'ltr',
    code: 'hi',
  },
  {
    name: 'Croatian',
    nativeName: 'Hrvatski',
    dir: 'ltr',
    code: 'hr',
  },
  {
    name: 'Hungarian',
    nativeName: 'Magyar',
    dir: 'ltr',
    code: 'hu',
  },
  {
    name: 'Indonesian',
    nativeName: 'Indonesia',
    dir: 'ltr',
    code: 'id',
  },
  {
    name: 'Icelandic',
    nativeName: 'Íslenska',
    dir: 'ltr',
    code: 'is',
  },
  {
    name: 'Italian',
    nativeName: 'Italiano',
    dir: 'ltr',
    code: 'it',
  },
  {
    name: 'Japanese',
    nativeName: '日本語',
    dir: 'ltr',
    code: 'ja',
  },
  {
    name: 'Korean',
    nativeName: '한국어',
    dir: 'ltr',
    code: 'ko',
  },
  {
    name: 'Lithuanian',
    nativeName: 'Lietuvių',
    dir: 'ltr',
    code: 'lt',
  },
  {
    name: 'Latvian',
    nativeName: 'Latviešu',
    dir: 'ltr',
    code: 'lv',
  },
  {
    name: 'Maltese',
    nativeName: 'Il-Malti',
    dir: 'ltr',
    code: 'mt',
  },
  {
    name: 'Malay',
    nativeName: 'Melayu',
    dir: 'ltr',
    code: 'ms',
  },
  {
    name: 'Hmong Daw',
    nativeName: 'Hmong Daw',
    dir: 'ltr',
    code: 'mww',
  },
  {
    name: 'Dutch',
    nativeName: 'Nederlands',
    dir: 'ltr',
    code: 'nl',
  },
  {
    name: 'Norwegian',
    nativeName: 'Norsk',
    dir: 'ltr',
    code: 'nb',
  },
  {
    name: 'Polish',
    nativeName: 'Polski',
    dir: 'ltr',
    code: 'pl',
  },
  {
    name: 'Portuguese (Brazil)',
    nativeName: 'Português (Brasil)',
    dir: 'ltr',
    code: 'pt',
  },
  {
    name: 'Romanian',
    nativeName: 'Română',
    dir: 'ltr',
    code: 'ro',
  },
  {
    name: 'Russian',
    nativeName: 'Русский',
    dir: 'ltr',
    code: 'ru',
  },
  {
    name: 'Slovak',
    nativeName: 'Slovenčina',
    dir: 'ltr',
    code: 'sk',
  },
  {
    name: 'Slovenian',
    nativeName: 'Slovenščina',
    dir: 'ltr',
    code: 'sl',
  },
  {
    name: 'Serbian (Latin)',
    nativeName: 'srpski (latinica)',
    dir: 'ltr',
    code: 'sr-Latn',
  },
  {
    name: 'Swedish',
    nativeName: 'Svenska',
    dir: 'ltr',
    code: 'sv',
  },
  {
    name: 'Swahili',
    nativeName: 'Kiswahili',
    dir: 'ltr',
    code: 'sw',
  },
  {
    name: 'Tamil',
    nativeName: 'தமிழ்',
    dir: 'ltr',
    code: 'ta',
  },
  {
    name: 'Thai',
    nativeName: 'ไทย',
    dir: 'ltr',
    code: 'th',
  },
  {
    name: 'Klingon (Latin)',
    nativeName: 'Klingon (Latin)',
    dir: 'ltr',
    code: 'tlh-Latn',
  },
  {
    name: 'Turkish',
    nativeName: 'Türkçe',
    dir: 'ltr',
    code: 'tr',
  },
  {
    name: 'Ukrainian',
    nativeName: 'Українська',
    dir: 'ltr',
    code: 'uk',
  },
  {
    name: 'Urdu',
    nativeName: 'اردو',
    dir: 'rtl',
    code: 'ur',
  },
  {
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    dir: 'ltr',
    code: 'vi',
  },
];

const appImages = {
  twitter: 'https://cdn.pubble.io/resources/dashboard/img/twitter-ico.png',
};

const constants = {
  allowedFileTypes:
    'png,gif,jpg,jpeg,pdf,doc,docx,xls,xlsx,ppt,pptx,mp3,mp4,mpeg,avi,wmv,mov,m4v,mkv,txt,csv',
};

const socketConfig = {
  pusher: {
    key: SOCKET_CONFIG.pusher.key,
    config: {
      ...SOCKET_CONFIG.pusher.config,
      encrypted: true,
    },
  },
  pubble: {
    key: SOCKET_CONFIG.pubble.key,
    config: {
      ...SOCKET_CONFIG.pubble.config,
      retryInterval: 10000,
      retryCount: 3,
      transports: ['websocket'],
    },
  },
};

const phoneCountryCode = [
  {name: 'Afghanistan (‫افغانستان‬‎)', countryCode: 'af', phoneCode: '93'},
  {name: 'Albania (Shqipëri)', countryCode: 'al', phoneCode: '355'},
  {name: 'Algeria (‫الجزائر‬‎)', countryCode: 'dz', phoneCode: '213'},
  {name: 'American Samoa', countryCode: 'as', phoneCode: '1684'},
  {name: 'Andorra', countryCode: 'ad', phoneCode: '376'},
  {name: 'Angola', countryCode: 'ao', phoneCode: '244'},
  {name: 'Anguilla', countryCode: 'ai', phoneCode: '1264'},
  {name: 'Antigua and Barbuda', countryCode: 'ag', phoneCode: '1268'},
  {name: 'Argentina', countryCode: 'ar', phoneCode: '54'},
  {name: 'Armenia (Հայաստան)', countryCode: 'am', phoneCode: '374'},
  {name: 'Aruba', countryCode: 'aw', phoneCode: '297'},
  {name: 'Australia', countryCode: 'au', phoneCode: '61'},
  {name: 'Austria (Österreich)', countryCode: 'at', phoneCode: '43'},
  {name: 'Azerbaijan (Azərbaycan)', countryCode: 'az', phoneCode: '994'},
  {name: 'Bahamas', countryCode: 'bs', phoneCode: '1242'},
  {name: 'Bahrain (‫البحرين‬‎)', countryCode: 'bh', phoneCode: '973'},
  {name: 'Bangladesh (বাংলাদেশ)', countryCode: 'bd', phoneCode: '880'},
  {name: 'Barbados', countryCode: 'bb', phoneCode: '1246'},
  {name: 'Belarus (Беларусь)', countryCode: 'by', phoneCode: '375'},
  {name: 'Belgium (België)', countryCode: 'be', phoneCode: '32'},
  {name: 'Belize', countryCode: 'bz', phoneCode: '501'},
  {name: 'Benin (Bénin)', countryCode: 'bj', phoneCode: '229'},
  {name: 'Bermuda', countryCode: 'bm', phoneCode: '1441'},
  {name: 'Bhutan (འབྲུག)', countryCode: 'bt', phoneCode: '975'},
  {name: 'Bolivia', countryCode: 'bo', phoneCode: '591'},
  {
    name: 'Bosnia and Herzegovina (Босна и Херцеговина)',
    countryCode: 'ba',
    phoneCode: '387',
  },
  {name: 'Botswana', countryCode: 'bw', phoneCode: '267'},
  {name: 'Brazil (Brasil)', countryCode: 'br', phoneCode: '55'},
  {name: 'British Indian Ocean Territory', countryCode: 'io', phoneCode: '246'},
  {name: 'British Virgin Islands', countryCode: 'vg', phoneCode: '1284'},
  {name: 'Brunei', countryCode: 'bn', phoneCode: '673'},
  {name: 'Bulgaria (България)', countryCode: 'bg', phoneCode: '359'},
  {name: 'Burkina Faso', countryCode: 'bf', phoneCode: '226'},
  {name: 'Burundi (Uburundi)', countryCode: 'bi', phoneCode: '257'},
  {name: 'Cambodia (កម្ពុជា)', countryCode: 'kh', phoneCode: '855'},
  {name: 'Cameroon (Cameroun)', countryCode: 'cm', phoneCode: '237'},
  {name: 'Canada', countryCode: 'ca', phoneCode: '1'},
  {name: 'Cape Verde (Kabu Verdi)', countryCode: 'cv', phoneCode: '238'},
  {name: 'Caribbean Netherlands', countryCode: 'bq', phoneCode: '599'},
  {name: 'Cayman Islands', countryCode: 'ky', phoneCode: '1345'},
  {
    name: 'Central African Republic (République centrafricaine)',
    countryCode: 'cf',
    phoneCode: '236',
  },
  {name: 'Chad (Tchad)', countryCode: 'td', phoneCode: '235'},
  {name: 'Chile', countryCode: 'cl', phoneCode: '56'},
  {name: 'China (中国)', countryCode: 'cn', phoneCode: '86'},
  {name: 'Colombia', countryCode: 'co', phoneCode: '57'},
  {name: 'Comoros (‫جزر القمر‬‎)', countryCode: 'km', phoneCode: '269'},
  {
    name: 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)',
    countryCode: 'cd',
    phoneCode: '243',
  },
  {
    name: 'Congo (Republic) (Congo-Brazzaville)',
    countryCode: 'cg',
    phoneCode: '242',
  },
  {name: 'Cook Islands', countryCode: 'ck', phoneCode: '682'},
  {name: 'Costa Rica', countryCode: 'cr', phoneCode: '506'},
  {name: 'Côte d’Ivoire', countryCode: 'ci', phoneCode: '225'},
  {name: 'Croatia (Hrvatska)', countryCode: 'hr', phoneCode: '385'},
  {name: 'Cuba', countryCode: 'cu', phoneCode: '53'},
  {name: 'Curaçao', countryCode: 'cw', phoneCode: '599'},
  {name: 'Cyprus (Κύπρος)', countryCode: 'cy', phoneCode: '357'},
  {
    name: 'Czech Republic (Česká republika)',
    countryCode: 'cz',
    phoneCode: '420',
  },
  {name: 'Denmark (Danmark)', countryCode: 'dk', phoneCode: '45'},
  {name: 'Djibouti', countryCode: 'dj', phoneCode: '253'},
  {name: 'Dominica', countryCode: 'dm', phoneCode: '1767'},
  {
    name: 'Dominican Republic (República Dominicana)',
    countryCode: 'do',
    phoneCode: '1',
  },
  {name: 'Ecuador', countryCode: 'ec', phoneCode: '593'},
  {name: 'Egypt (‫مصر‬‎)', countryCode: 'eg', phoneCode: '20'},
  {name: 'El Salvador', countryCode: 'sv', phoneCode: '503'},
  {
    name: 'Equatorial Guinea (Guinea Ecuatorial)',
    countryCode: 'gq',
    phoneCode: '240',
  },
  {name: 'Eritrea', countryCode: 'er', phoneCode: '291'},
  {name: 'Estonia (Eesti)', countryCode: 'ee', phoneCode: '372'},
  {name: 'Ethiopia', countryCode: 'et', phoneCode: '251'},
  {
    name: 'Falkland Islands (Islas Malvinas)',
    countryCode: 'fk',
    phoneCode: '500',
  },
  {name: 'Faroe Islands (Føroyar)', countryCode: 'fo', phoneCode: '298'},
  {name: 'Fiji', countryCode: 'fj', phoneCode: '679'},
  {name: 'Finland (Suomi)', countryCode: 'fi', phoneCode: '358'},
  {name: 'France', countryCode: 'fr', phoneCode: '33'},
  {
    name: 'French Guiana (Guyane française)',
    countryCode: 'gf',
    phoneCode: '594',
  },
  {
    name: 'French Polynesia (Polynésie française)',
    countryCode: 'pf',
    phoneCode: '689',
  },
  {name: 'Gabon', countryCode: 'ga', phoneCode: '241'},
  {name: 'Gambia', countryCode: 'gm', phoneCode: '220'},
  {name: 'Georgia (საქართველო)', countryCode: 'ge', phoneCode: '995'},
  {name: 'Germany (Deutschland)', countryCode: 'de', phoneCode: '49'},
  {name: 'Ghana (Gaana)', countryCode: 'gh', phoneCode: '233'},
  {name: 'Gibraltar', countryCode: 'gi', phoneCode: '350'},
  {name: 'Greece (Ελλάδα)', countryCode: 'gr', phoneCode: '30'},
  {name: 'Greenland (Kalaallit Nunaat)', countryCode: 'gl', phoneCode: '299'},
  {name: 'Grenada', countryCode: 'gd', phoneCode: '1473'},
  {name: 'Guadeloupe', countryCode: 'gp', phoneCode: '590'},
  {name: 'Guam', countryCode: 'gu', phoneCode: '1671'},
  {name: 'Guatemala', countryCode: 'gt', phoneCode: '502'},
  {name: 'Guinea (Guinée)', countryCode: 'gn', phoneCode: '224'},
  {name: 'Guinea-Bissau (Guiné Bissau)', countryCode: 'gw', phoneCode: '245'},
  {name: 'Guyana', countryCode: 'gy', phoneCode: '592'},
  {name: 'Haiti', countryCode: 'ht', phoneCode: '509'},
  {name: 'Honduras', countryCode: 'hn', phoneCode: '504'},
  {name: 'Hong Kong (香港)', countryCode: 'hk', phoneCode: '852'},
  {name: 'Hungary (Magyarország)', countryCode: 'hu', phoneCode: '36'},
  {name: 'Iceland (Ísland)', countryCode: 'is', phoneCode: '354'},
  {name: 'India (भारत)', countryCode: 'in', phoneCode: '91'},
  {name: 'Indonesia', countryCode: 'id', phoneCode: '62'},
  {name: 'Iran (‫ایران‬‎)', countryCode: 'ir', phoneCode: '98'},
  {name: 'Iraq (‫العراق‬‎)', countryCode: 'iq', phoneCode: '964'},
  {name: 'Ireland', countryCode: 'ie', phoneCode: '353'},
  {name: 'Israel (‫ישראל‬‎)', countryCode: 'il', phoneCode: '972'},
  {name: 'Italy (Italia)', countryCode: 'it', phoneCode: '39'},
  {name: 'Jamaica', countryCode: 'jm', phoneCode: '1876'},
  {name: 'Japan (日本)', countryCode: 'jp', phoneCode: '81'},
  {name: 'Jordan (‫الأردن‬‎)', countryCode: 'jo', phoneCode: '962'},
  {name: 'Kazakhstan (Казахстан)', countryCode: 'kz', phoneCode: '7'},
  {name: 'Kenya', countryCode: 'ke', phoneCode: '254'},
  {name: 'Kiribati', countryCode: 'ki', phoneCode: '686'},
  {name: 'Kuwait (‫الكويت‬‎)', countryCode: 'kw', phoneCode: '965'},
  {name: 'Kyrgyzstan (Кыргызстан)', countryCode: 'kg', phoneCode: '996'},
  {name: 'Laos (ລາວ)', countryCode: 'la', phoneCode: '856'},
  {name: 'Latvia (Latvija)', countryCode: 'lv', phoneCode: '371'},
  {name: 'Lebanon (‫لبنان‬‎)', countryCode: 'lb', phoneCode: '961'},
  {name: 'Lesotho', countryCode: 'ls', phoneCode: '266'},
  {name: 'Liberia', countryCode: 'lr', phoneCode: '231'},
  {name: 'Libya (‫ليبيا‬‎)', countryCode: 'ly', phoneCode: '218'},
  {name: 'Liechtenstein', countryCode: 'li', phoneCode: '423'},
  {name: 'Lithuania (Lietuva)', countryCode: 'lt', phoneCode: '370'},
  {name: 'Luxembourg', countryCode: 'lu', phoneCode: '352'},
  {name: 'Macau (澳門)', countryCode: 'mo', phoneCode: '853'},
  {name: 'Macedonia (FYROM) (Македонија)', countryCode: 'mk', phoneCode: '389'},
  {name: 'Madagascar (Madagasikara)', countryCode: 'mg', phoneCode: '261'},
  {name: 'Malawi', countryCode: 'mw', phoneCode: '265'},
  {name: 'Malaysia', countryCode: 'my', phoneCode: '60'},
  {name: 'Maldives', countryCode: 'mv', phoneCode: '960'},
  {name: 'Mali', countryCode: 'ml', phoneCode: '223'},
  {name: 'Malta', countryCode: 'mt', phoneCode: '356'},
  {name: 'Marshall Islands', countryCode: 'mh', phoneCode: '692'},
  {name: 'Martinique', countryCode: 'mq', phoneCode: '596'},
  {name: 'Mauritania (‫موريتانيا‬‎)', countryCode: 'mr', phoneCode: '222'},
  {name: 'Mauritius (Moris)', countryCode: 'mu', phoneCode: '230'},
  {name: 'Mexico (México)', countryCode: 'mx', phoneCode: '52'},
  {name: 'Micronesia', countryCode: 'fm', phoneCode: '691'},
  {name: 'Moldova (Republica Moldova)', countryCode: 'md', phoneCode: '373'},
  {name: 'Monaco', countryCode: 'mc', phoneCode: '377'},
  {name: 'Mongolia (Монгол)', countryCode: 'mn', phoneCode: '976'},
  {name: 'Montenegro (Crna Gora)', countryCode: 'me', phoneCode: '382'},
  {name: 'Montserrat', countryCode: 'ms', phoneCode: '1664'},
  {name: 'Morocco (‫المغرب‬‎)', countryCode: 'ma', phoneCode: '212'},
  {name: 'Mozambique (Moçambique)', countryCode: 'mz', phoneCode: '258'},
  {name: 'Myanmar (Burma) (မြန်မာ)', countryCode: 'mm', phoneCode: '95'},
  {name: 'Namibia (Namibië)', countryCode: 'na', phoneCode: '264'},
  {name: 'Nauru', countryCode: 'nr', phoneCode: '674'},
  {name: 'Nepal (नेपाल)', countryCode: 'np', phoneCode: '977'},
  {name: 'Netherlands (Nederland)', countryCode: 'nl', phoneCode: '31'},
  {
    name: 'New Caledonia (Nouvelle-Calédonie)',
    countryCode: 'nc',
    phoneCode: '687',
  },
  {name: 'New Zealand', countryCode: 'nz', phoneCode: '64'},
  {name: 'Nicaragua', countryCode: 'ni', phoneCode: '505'},
  {name: 'Niger (Nijar)', countryCode: 'ne', phoneCode: '227'},
  {name: 'Nigeria', countryCode: 'ng', phoneCode: '234'},
  {name: 'Niue', countryCode: 'nu', phoneCode: '683'},
  {name: 'Norfolk Island', countryCode: 'nf', phoneCode: '672'},
  {
    name: 'North Korea (조선 민주주의 인민 공화국)',
    countryCode: 'kp',
    phoneCode: '850',
  },
  {name: 'Northern Mariana Islands', countryCode: 'mp', phoneCode: '1670'},
  {name: 'Norway (Norge)', countryCode: 'no', phoneCode: '47'},
  {name: 'Oman (‫عُمان‬‎)', countryCode: 'om', phoneCode: '968'},
  {name: 'Pakistan (‫پاکستان‬‎)', countryCode: 'pk', phoneCode: '92'},
  {name: 'Palau', countryCode: 'pw', phoneCode: '680'},
  {name: 'Palestine (‫فلسطين‬‎)', countryCode: 'ps', phoneCode: '970'},
  {name: 'Panama (Panamá)', countryCode: 'pa', phoneCode: '507'},
  {name: 'Papua New Guinea', countryCode: 'pg', phoneCode: '675'},
  {name: 'Paraguay', countryCode: 'py', phoneCode: '595'},
  {name: 'Peru (Perú)', countryCode: 'pe', phoneCode: '51'},
  {name: 'Philippines', countryCode: 'ph', phoneCode: '63'},
  {name: 'Poland (Polska)', countryCode: 'pl', phoneCode: '48'},
  {name: 'Portugal', countryCode: 'pt', phoneCode: '351'},
  {name: 'Puerto Rico', countryCode: 'pr', phoneCode: '1'},
  {name: 'Qatar (‫قطر‬‎)', countryCode: 'qa', phoneCode: '974'},
  {name: 'Réunion (La Réunion)', countryCode: 're', phoneCode: '262'},
  {name: 'Romania (România)', countryCode: 'ro', phoneCode: '40'},
  {name: 'Russia (Россия)', countryCode: 'ru', phoneCode: '7'},
  {name: 'Rwanda', countryCode: 'rw', phoneCode: '250'},
  {
    name: 'Saint Barthélemy (Saint-Barthélemy)',
    countryCode: 'bl',
    phoneCode: '590',
  },
  {name: 'Saint Helena', countryCode: 'sh', phoneCode: '290'},
  {name: 'Saint Kitts and Nevis', countryCode: 'kn', phoneCode: '1869'},
  {name: 'Saint Lucia', countryCode: 'lc', phoneCode: '1758'},
  {
    name: 'Saint Martin (Saint-Martin (partie française))',
    countryCode: 'mf',
    phoneCode: '590',
  },
  {
    name: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
    countryCode: 'pm',
    phoneCode: '508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    countryCode: 'vc',
    phoneCode: '1784',
  },
  {name: 'Samoa', countryCode: 'ws', phoneCode: '685'},
  {name: 'San Marino', countryCode: 'sm', phoneCode: '378'},
  {
    name: 'São Tomé and Príncipe (São Tomé e Príncipe)',
    countryCode: 'st',
    phoneCode: '239',
  },
  {
    name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    countryCode: 'sa',
    phoneCode: '966',
  },
  {name: 'Senegal (Sénégal)', countryCode: 'sn', phoneCode: '221'},
  {name: 'Serbia (Србија)', countryCode: 'rs', phoneCode: '381'},
  {name: 'Seychelles', countryCode: 'sc', phoneCode: '248'},
  {name: 'Sierra Leone', countryCode: 'sl', phoneCode: '232'},
  {name: 'Singapore', countryCode: 'sg', phoneCode: '65'},
  {name: 'Sint Maarten', countryCode: 'sx', phoneCode: '1721'},
  {name: 'Slovakia (Slovensko)', countryCode: 'sk', phoneCode: '421'},
  {name: 'Slovenia (Slovenija)', countryCode: 'si', phoneCode: '386'},
  {name: 'Solomon Islands', countryCode: 'sb', phoneCode: '677'},
  {name: 'Somalia (Soomaaliya)', countryCode: 'so', phoneCode: '252'},
  {name: 'South Africa', countryCode: 'za', phoneCode: '27'},
  {name: 'South Korea (대한민국)', countryCode: 'kr', phoneCode: '82'},
  {name: 'South Sudan (‫جنوب السودان‬‎)', countryCode: 'ss', phoneCode: '211'},
  {name: 'Spain (España)', countryCode: 'es', phoneCode: '34'},
  {name: 'Sri Lanka (ශ්‍රී ලංකාව)', countryCode: 'lk', phoneCode: '94'},
  {name: 'Sudan (‫السودان‬‎)', countryCode: 'sd', phoneCode: '249'},
  {name: 'Suriname', countryCode: 'sr', phoneCode: '597'},
  {name: 'Swaziland', countryCode: 'sz', phoneCode: '268'},
  {name: 'Sweden (Sverige)', countryCode: 'se', phoneCode: '46'},
  {name: 'Switzerland (Schweiz)', countryCode: 'ch', phoneCode: '41'},
  {name: 'Syria (‫سوريا‬‎)', countryCode: 'sy', phoneCode: '963'},
  {name: 'Taiwan (台灣)', countryCode: 'tw', phoneCode: '886'},
  {name: 'Tajikistan', countryCode: 'tj', phoneCode: '992'},
  {name: 'Tanzania', countryCode: 'tz', phoneCode: '255'},
  {name: 'Thailand (ไทย)', countryCode: 'th', phoneCode: '66'},
  {name: 'Timor-Leste', countryCode: 'tl', phoneCode: '670'},
  {name: 'Togo', countryCode: 'tg', phoneCode: '228'},
  {name: 'Tokelau', countryCode: 'tk', phoneCode: '690'},
  {name: 'Tonga', countryCode: 'to', phoneCode: '676'},
  {name: 'Trinidad and Tobago', countryCode: 'tt', phoneCode: '1868'},
  {name: 'Tunisia (‫تونس‬‎)', countryCode: 'tn', phoneCode: '216'},
  {name: 'Turkey (Türkiye)', countryCode: 'tr', phoneCode: '90'},
  {name: 'Turkmenistan', countryCode: 'tm', phoneCode: '993'},
  {name: 'Turks and Caicos Islands', countryCode: 'tc', phoneCode: '1649'},
  {name: 'Tuvalu', countryCode: 'tv', phoneCode: '688'},
  {name: 'U.S. Virgin Islands', countryCode: 'vi', phoneCode: '1340'},
  {name: 'Uganda', countryCode: 'ug', phoneCode: '256'},
  {name: 'Ukraine (Україна)', countryCode: 'ua', phoneCode: '380'},
  {
    name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
    countryCode: 'ae',
    phoneCode: '971',
  },
  {name: 'United Kingdom', countryCode: 'gb', phoneCode: '44'},
  {name: 'United States', countryCode: 'us', phoneCode: '1'},
  {name: 'Uruguay', countryCode: 'uy', phoneCode: '598'},
  {name: 'Uzbekistan (Oʻzbekiston)', countryCode: 'uz', phoneCode: '998'},
  {name: 'Vanuatu', countryCode: 'vu', phoneCode: '678'},
  {
    name: 'Vatican City (Città del Vaticano)',
    countryCode: 'va',
    phoneCode: '39',
  },
  {name: 'Venezuela', countryCode: 've', phoneCode: '58'},
  {name: 'Vietnam (Việt Nam)', countryCode: 'vn', phoneCode: '84'},
  {name: 'Wallis and Futuna', countryCode: 'wf', phoneCode: '681'},
  {name: 'Yemen (‫اليمن‬‎)', countryCode: 'ye', phoneCode: '967'},
  {name: 'Zambia', countryCode: 'zm', phoneCode: '260'},
  {name: 'Zimbabwe', countryCode: 'zw', phoneCode: '263'},
];

export {
  Discriminator,
  pageSize,
  manageApps,
  translations,
  appImages,
  constants,
  socketConfig,
  phoneCountryCode,
};
