export const AuthState = {
  SET_INIT: 'SET_INIT',
  SET_USER: 'SET_USER',
  SET_COMMUNITY: 'SET_COMMUNITY',
  SET_EVENTS: 'SET_EVENTS',
  SET_SELECTED_EVENT: 'SET_SELECTED_EVENT',
  CLEAR_USER: 'CLEAR_USER',
};

export const EventsState = {
  SET_STREAM: 'SET_STREAM',
};

export const CollectionsState = {
  SET_INIT: 'SET_INIT',
  SET_USER_COLLECTION: 'SET_USER_COLLECTION',
  SET_GROUP_COLLECTION: 'SET_GROUP_COLLECTION',
  UPDATE_COLLECTION: 'UPDATE_COLLECTION',
};
