export const AuthState = {
  SET_INIT: 'SET_INIT',
  SET_USER: 'SET_USER',
  SET_COMMUNITY: 'SET_COMMUNITY',
  SET_EVENTS: 'SET_EVENTS',
  SET_SELECTED_EVENT: 'SET_SELECTED_EVENT',
  CLEAR_USER: 'CLEAR_USER',
};

export const EventsState = {
  SET_STREAM: 'SET_STREAM',
  APPROVE_DISAPPROVE_STREAM: 'APPROVE_DISAPPROVE_STREAM',
  DELETE_STREAM: 'DELETE_STREAM',
  STAR_STREAM: 'STAR_STREAM',
  LOCK_STREAM: 'LOCK_STREAM',
  CLOSE_STREAM: 'CLOSE_STREAM',
  UPDATE_ASSIGN: 'UPDATE_ASSIGN',
  REMOVE_ASSIGN: 'REMOVE_ASSIGN',
  CLOSE_POLL_VOTING: 'CLOSE_POLL_VOTING',
  VOTING_ACTION: 'VOTING_ACTION',
  ADD_NEW_ANNOUNCEMENT: 'ADD_NEW_ANNOUNCEMENT',
  GET_STATE_COUNTRY_IP: 'GET_STATE_COUNTRY_IP',
  UPDATE_NAME_CHATMENU: 'UPDATE_NAME_CHATMENU',
  UPDATE_EMAIL_CHATMENU: 'UPDATE_EMAIL_CHATMENU',
  UPDATE_PHONE_CHATMENU: 'UPDATE_PHONE_CHATMENU',
  ADD_NEW_TAGS: 'ADD_NEW_TAGS',
  CLOSE_QUESTION: 'CLOSE_QUESTION',
};

export const CollectionsState = {
  SET_INIT: 'SET_INIT',
  SET_USER_COLLECTION: 'SET_USER_COLLECTION',
  SET_GROUP_COLLECTION: 'SET_GROUP_COLLECTION',
};
