export const AuthState = {
  SET_INIT: 'SET_INIT',
  SET_USER: 'SET_USER',
  SET_COMMUNITY: 'SET_COMMUNITY',
  SET_EVENTS: 'SET_EVENTS',
  SET_SELECTED_EVENT: 'SET_SELECTED_EVENT',
  CLEAR_USER: 'CLEAR_USER',
};
export const EventsState = {
  GET_STREAM: 'GET_STREAM',
};
